import { useEffect, useState } from "react"

export const useLocalStorage = (key) => {
  const [value, setValue] = useState()

  useEffect(() => {
    if (localStorage.getItem(key) === null && key === "boxes") {
      localStorage.setItem(
        key,
        JSON.stringify({
          0: [
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
          ],
          1: [
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
          ],
          2: [
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
          ],
          3: [
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
            { sprite: "" },
          ],
        })
      )
    } else if (localStorage.getItem(key) !== null && key === "boxes") {
      setValue(JSON.parse(localStorage.getItem(key)))
    }

    if (localStorage.getItem(key) === null && key === "team") {
      localStorage.setItem(
        key,
        JSON.stringify([
          { sprite: "" },
          { sprite: "" },
          { sprite: "" },
          { sprite: "" },
          { sprite: "" },
          { sprite: "" },
        ])
      )
    } else if (localStorage.getItem(key) !== null && key === "team") {
      setValue(JSON.parse(localStorage.getItem(key)))
    }
  }, [key])

  return [value]
}
