export const getBoxes = () => {
  if (localStorage.getItem("boxes") === null) {
    localStorage.setItem(
      "boxes",
      JSON.stringify({
        1: [
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
        ],
        2: [
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
        ],
        3: [
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
        ],
        4: [
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
        ],
        5: [
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
        ],
        6: [
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
        ],
        7: [
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
        ],
        8: [
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
          { sprite: "", shiny: false, gender: "", name: "" },
        ],
      })
    )
    return JSON.parse(localStorage.getItem("boxes"))
  } else if (localStorage.getItem("boxes") !== null) {
    return JSON.parse(localStorage.getItem("boxes"))
  }
}

export const getTeam = () => {
  if (localStorage.getItem("team") === null) {
    localStorage.setItem(
      "team",
      JSON.stringify([
        { sprite: "", shiny: false, gender: "", name: "" },
        { sprite: "", shiny: false, gender: "", name: "" },
        { sprite: "", shiny: false, gender: "", name: "" },
        { sprite: "", shiny: false, gender: "", name: "" },
        { sprite: "", shiny: false, gender: "", name: "" },
        { sprite: "", shiny: false, gender: "", name: "" },
      ])
    )
    return JSON.parse(localStorage.getItem("team"))
  } else if (localStorage.getItem("team") !== null) {
    return JSON.parse(localStorage.getItem("team"))
  }
}
